server:
  port: 8085
eureka:
  client:
    serviceUrl:
       defaultZone: http://localhost:8082/eureka/
spring:
  data:
    mongodb:
      username: root
      database: nttbank
      password: admin
      port: '27017'
      host: localhost
type:
  transaction:
    exception: Unknown transaction type
dup:
  business:
    exception: Business already registered
  person:
    exception: Person already registered
balance:
  transaction:
    exception: Not enough funds
logging:
  config: classpath:logback.xml